version: "3.7"
services:
  postgres_register:
    container_name: postgres_register_irest
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: register
      POSTGRES_PASSWORD: register
    ports:
      - "5432:5432"
  keycloak_irest:
    container_name: keycloak_irest
    image: jboss/keycloak:12.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
