version: "3.7"
services:
  postgres_register:
    container_name: postgres_register_irest
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: register
      POSTGRES_PASSWORD: register
    ports:
      - "5432:5432"